### ISSUE TITLE
how to  set nomad_options with inventory vars on hosts to enable driver.raw_exec.enable= 1

### ISSUE THREAD

**Issue by rinetd** [brianshumate/ansible-nomad#43]
>

**Comment by Woutifier** [comment]
```
[nomad_instances:vars]
nomad_options={'driver.raw_exec.enable': '1'}
```

**Comment by albttx** [comment]
Is this still working for you ? It's not for me with nomad `0.9.3`

Now raw_exec is a "plugin" cf: https://www.nomadproject.io/docs/drivers/raw_exec.html#client-requirements

**Comment by jason-riddle** [comment]
@albttx For versions v0.9.0 and up, use the following syntax:

```yml
nomad_config_custom:
  plugin:
    raw_exec:
      config:
        enabled: true
```
